name: Test Workflow

on: push

jobs:
    buil_and_test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4.2.1
              # with: ${{}}

            - name: List files
              run: ls 

            - name: Executing Shell Script
              run: 
                chmod +x shell-script.sh
                ./shell-script.sh
