name: Test Workflow

on: push

jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.1
      # with: ${{}}

    - name: List files
      run: ls 

    - name: Executing Shell Script
      run: 
        chmod +x shell-script.sh
        ./shell-script.sh

    - name: Upload README.md file
      uses: actions/upload-artifact@v4
      with:
        name: README.md artifact
        path: README.md

  test_job: 
    needs: build_job
    runs-on: ubuntu-latest
    steps:
    - name: Download README.md file   
      uses: actions/download-artifact@v4
      with:
        name: README.md artifact

    - name: sleep for 10 seconds
      run: sleep 10

    - name: List files in root directory
      run: ls -la

    - name: Test file exists
      run: test -f README.md

    - name: Test keyword exists
      run: grep -i "test" README.md

  deploy_job:
    needs: [test_job]
    runs-on: ubuntu-latest
    steps:
    - name: Download README.md file     
      uses: actions/download-artifact@v4
      with:
        name: README.md artifact

    - name: Read file
      run: cat README.md

    - name: Deploy
      run: echo deploying ...                             