name: Test Workflow

on: push

jobs:
    buil_and_test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4.2.1
              # with: ${{}}
            
            - name: Welcome message
              run: echo "Hello World"

            - name: List files
              run: ls

            - name: Read file
              run: cat README.md